source 'https://rubygems.org'
#ruby '2.2.1' (Uncomment For Production)

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'

# Use postgresql as the database for Active Record
gem 'pg'
gem 'rails_12factor', group: :production
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
gem 'coffee-script-source', '1.8.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'bootstrap-sass'
gem "therubyracer" , :platform => :ruby
#
gem "less-rails"
gem "twitter-bootstrap-rails"
gem 'bcrypt', :require => 'bcrypt'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
#paperclip for adding images
gem "paperclip", "~> 4.3"
#article tagging
gem 'acts-as-taggable-on', '~> 3.4'

gem 'puma'
# Use unicorn as the app server
# gem 'unicorn'
#User authentication
gem 'devise'
gem 'devise-token_authenticatable'
gem 'cancan'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Some middleware to allow requests from different origins
gem 'rack-cors', :require => 'rack/cors'

source "https://rails-assets.org" do
  gem "rails-assets-angular-devise"
end
# Use debugger
# gem 'debugger', group: [:development, :test]

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin]
